language: csharp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      dotnet: 3.0.100
      mono: none

branches:
  only:
    - master
    - dev

script:
  - dotnet restore
  - dotnet build
  - dotnet test

global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true