language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
	  sudo: required
      dotnet: 2.2.202
      mono: latest


branches:
  only:
    - master

script:
	- dotnet restore
	- dotnet test
