name: .NET Core

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup .NET Core
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: 5.0.102
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Build NuGet Packages
        run: dotnet pack --output nuget-packages --configuration Release
      - name: Deploy NuGet Packages
        run: dotnet nuget push **\*.nupkg -k ${{ secrets.NUGET_KEY }} -s "https://api.nuget.org/v3/index.json" --skip-duplicate
        working-directory: nuget-packages
