name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.401
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Build NuGet Packages
        run: dotnet pack -o ./publish --configuration Release
      - name: Deploy NuGet Packages
        uses: tanaka-takayoshi/nuget-publish-to-github-packages-action@v2.1
        with:
          nupkg-path:  './publish/*.nupkg'
          repo-owner:  'mo3in'
          gh-user:  'mo3in'
          token:  ${{ secrets.NUGET_KEY }}